USE wq8968a3nb27ujgp;
SELECT * FROM userInfo;


DROP TABLE IF EXISTS userInfo;

CREATE TABLE userInfo (
id INT AUTO_INCREMENT NOT NULL,
user_name VARCHAR(255),
createdAt TIMESTAMP NOT NULL,
PRIMARY KEY(id)
);

